### ISSUE TITLE
Release tx's ID not from Eth contract

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#58]
As previously discussed [here](https://github.com/oasisprotocol/oasis-bridge/issues/41#issuecomment-823894568), when composing Oasis tx request, the tx ID is from ETH contract's nonce, but it would hit "invalid sequence number" under some scenario:  so in the [commit](https://github.com/octopus-network/oasis-ethereum/commit/4ca5c13a60834001d03ea5f8e9f0194b2ffefc81), the tx ID is queried from Oasis bridge runtime, instead of from ETH contract; Code changes [here](https://github.com/octopus-network/oasis-ethereum/commit/4ca5c13a60834001d03ea5f8e9f0194b2ffefc81#diff-f6360600746dcec88f8cc5a6262deceece08d0b2f3ca9292fd7d66c86c8ebc15R569) and  [here](https://github.com/octopus-network/oasis-ethereum/commit/4ca5c13a60834001d03ea5f8e9f0194b2ffefc81#diff-f6360600746dcec88f8cc5a6262deceece08d0b2f3ca9292fd7d66c86c8ebc15R581).
 
If set the tx ID to the value from ETH contract's nonce, there is "invalid sequnce number" error in the scenario below:
* TX0: User A transfers 0.5 ETH to Oasis's User B account; In the release tx in Oasis, the ID is 0; Successful;
* TX1: User B transfers 0.1 oETH to Ethereum; 
* TX2: User B transfers 0.2 oETH to Ethereum; 
* TX3: Before requests of TX1 & TX2 reach Ethereum, User A transfers 0.7 ETH to Oasis's User B account; The release tx request to Oasis hit "invalid sequence number"; The ID in the tx request is 1, but I guess Oasis bridge paratime expects the ID to be 3.

Any suggestion?

**Comment by kostko** [comment]
Note that there are two different sets of sequence numbers, one is for incoming events and the other one is for outgoing events. So if I understand the above correctly, you have these things happening in the ParaTime module:
* Initial state is both `NEXT_IN_SEQUENCE` and `NEXT_OUT_SEQUENCE` set to 0.
* Tx0: `bridge.Release` finalizes and bumps `NEXT_IN_SEQUENCE` to 1.
* Tx1: `bridge.Lock` bumps `NEXT_OUT_SEQUENCE` to 1.
* Tx2: `bridge.Lock` bumps `NEXT_OUT_SEQUENCE` to 2.
* Tx3: `bridge.Release` should use the sequence number of 1 (and not 3).

Since there are two sets of sequence numbers, this should already behave correctly and the module should expect the ID to be 1.

Would be great if you could provide a minimal example (e.g. Go code) that can reproduce this.

**Comment by livelybug** [comment]
It turns out it's due to the [incorrect nonce](https://github.com/octopus-network/oasis-ethereum/commit/4ca5c13a60834001d03ea5f8e9f0194b2ffefc81#diff-f6360600746dcec88f8cc5a6262deceece08d0b2f3ca9292fd7d66c86c8ebc15R586). After setting the correct nonce, the "invalid sequence number" is gone.

> As we discussed before, witnesses must take care to properly order events and wait for the respective Release events before submitting the next release.

Yes, it's implemented.
@kostko One possible side effect of the implementation: If Tx0( bridge.Release) fails, the witness will keep re-sending Tx0, until Tx0 succeeds or manual intervention.
