### ISSUE TITLE
release doesn't work without lock

### ISSUE THREAD

**Issue by burtchensu** [oasisprotocol/oasis-bridge#6]
In my testing, 
if the lock relevant code ([this line](https://github.com/oasisprotocol/oasis-bridge/tree/a103eec5f8aa7d79a2e6e89baca89b7a24b41de0/examples/user-witness-flow#L269) to [this line](https://github.com/oasisprotocol/oasis-bridge/tree/a103eec5f8aa7d79a2e6e89baca89b7a24b41de0/examples/user-witness-flow#L385)) in witness is commented, 
the submission of [release tx](https://github.com/oasisprotocol/oasis-bridge/tree/a103eec5f8aa7d79a2e6e89baca89b7a24b41de0/examples/user-witness-flow#L403) doesn't get any reply.
Is it expected behavior for now?

**Comment by kostko** [comment]
With the previous version there was no support for using the correct transaction nonce and there was no local transaction checks which is why you did not get a response.

The updated PR #1 now contains support for automatically querying nonces so release call should work. This requires https://github.com/oasisprotocol/oasis-core/pull/3662 to be merged first in Oasis Core (or using that branch of Oasis Core).

**Comment by burtchensu** [comment]
The revison of core 9998deaee02ff1fa9a549d42791449013ca8662a resolved it.
